name: Action_test
run-name: whole_ci_cd
on: [push, pull_request]
env:
  runner-name: self-hosted
jobs:
  test-plan: 
      runs-on: ${{env.runner-name}}
      env:
        elapsed_time: N/A
      steps:
        - name: Set Job Start Time
          run: echo "start_time=$(date +%s)" >> $GITHUB_ENV
        - name: Checkout project file
          uses: actions/checkout@v4
        - name: delay
          run: sleep 3
        - name: Calculate Running Time
          run: |
            current_time=$(date +%s)
            running_time=$((current_time - start_time))
            if [ $running_time > 60 ]
            then
              minute=$(( running_time / 60))
              second=$(( running_time % 60))
              echo "elapsed_time=$((minute)) min $((second)) sec" >> $GITHUB_ENV
            fi
        - name: Time
          if: always()
          run: |
            echo $elapsed_time
  deploy_apps1:
    runs-on: ${{env.runner-name}}
    needs: test-plan
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/deploy'
    steps:
      - name: Test run
        run: echo "This is a test"
      - name: Run sh
        working-directory: ./sc
        run: ./test.sh
  deploy_apps2:
    runs-on: ${{env.runner-name}}
    needs: test-plan
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/deploy'
    steps:
      - name: Test run
        run: echo "This is a test"
      - name: Run sh
        working-directory: ./sc
        run: ./test.sh
  OAO:
    runs-on: ${{env.runner-name}}
    needs: [deploy_apps1, deploy_apps2]
    steps:
      - name: Test run
        run: echo "This is a test"
      - name: Run sh
        working-directory: ./sc
        run: ./test.sh

