name: Action_test_1
run-name: whole_ci_cd
on: push
env:
  test_1: askldjkls
jobs:
  job_1: 
    runs-on: ${{ vars.RUNNER_LABEL }}
    env:
      elapsed_time: N/A
    outputs:
      out_1: ${{ steps.add-output.outputs.out_12 }}
    steps:
      - name: Set Job Start Time
        run: echo "start_time=$(date +%s)" >> $GITHUB_ENV
      - name: Checkout project file
        uses: actions/checkout@v4
      - name: delay
        run: sleep 3
      - name: Add output
        id: add-output
        run: echo "out_12=$(date +%s)" >> "$GITHUB_OUTPUT"
      - name: Calculate Running Time
        run: |
          current_time=$(date +%s)
          running_time=$((current_time - start_time))
          if [ $running_time > 60 ]
          then
            minute=$(( running_time / 60))
            second=$(( running_time % 60))
            echo "elapsed_time=$((minute)) min $((second)) sec" >> $GITHUB_ENV
          fi
      - name: Time
        if: always()
        run: |
          echo $elapsed_time
  job_2:
    runs-on: ${{ vars.RUNNER_LABEL }}
    steps:
      - name: print output
        run: echo "Hello world"

  job_3:
    runs-on: ${{ vars.RUNNER_LABEL }}
    needs: [job_1, job_2]
    steps:
      - name: print output
        run: echo "${{ needs.job_1.outputs.out_1 }}"






  # deploy_apps1:
  #   runs-on: self-hosted
  #   needs: test-plan
  #   if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/deploy'
  #   steps:
  #     - name: Test run
  #       run: echo "This is a test"
  #     - name: Run sh
  #       working-directory: ./sc
  #       run: ./test.sh
  # deploy_apps2:
  #   runs-on: self-hosted
  #   needs: test-plan
  #   if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/deploy'
  #   steps:
  #     - name: Test run
  #       run: echo "This is a test"
  #     - name: Run sh
  #       working-directory: ./sc
  #       run: ./test.sh
  # OAO:
  #   runs-on: self-hosted
  #   needs: [deploy_apps1, deploy_apps2]
  #   steps:
  #     - name: Test run
  #       run: echo "This is a test"
  #     - name: Run sh
  #       working-directory: ./sc
  #       run: ./test.sh

